# -*- coding: utf-8 -*-
"""yudale Ezdrama Parser in Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVoTAKdObctt8pcUNUiCAtbh8PTMsfHG

# How to use this notebook
Just two simple steps:

### 1. First run ▶️  this cell below and **upload your ezdrama file in txt format** (if you're unsure how it should look, check the example [here](https://raw.githubusercontent.com/dracor-org/ezdrama/main/sample.txt))
"""

#RUN ME!
 #estee: is it not necessary to run this cell
#from google.colab import files
#uploaded = files.upload()

"""### 2. Run ▶️ this cell below.

The resulting TEI/XML should start downloading once it's done
"""

# imports
#from google.colab import files
import re
from datetime import datetime
#!pip install transliterate
from transliterate import translit
#!pip install yiddish
import yiddish
#!pip install bs4
from bs4 import BeautifulSoup, Tag
# get the parser code:
#!wget https://raw.githubusercontent.com/dracor-org/ezdrama/main/parser.py
#!wget https://raw.githubusercontent.com/dracor-org/ezdrama/main/parser.py
from parser import Parser # imports the EzDrama parser from the local parser.py file
#filepath = list(uploaded.keys())[0] # gets the name of the file you uploaded
#estee: get .txt base
#!wget https://raw.githubusercontent.com/esteeschwarz/dybbuk-cor/main/convert/actuel/TEI/yudale_ezd_pre_semicor_003.txt
#!wget https://raw.githubusercontent.com/esteeschwarz/dybbuk-cor/main/convert/actuel/TEI/yudale_ezd_pre_semicor_002.txt
filepath = "TEI/yudale_ezd_pre_semicor_003.txt" # gets the name of the file you uploaded
parser = Parser() # initializes the parser instance
parser.process_file(filepath) # parses your file to tei/xml
#parser.process_file("yudale_ezd_pre_semicor_003.txt") # parses your file to tei/xml
#files.download(parser.outputname) # downloads the tei/xml
#!rm yudale_ezd_pre_semicor_003.txt

